### PR TITLE
Add install plan for metadeploy

### PR DESCRIPTION
**Pull request by davisagli**
This defines the steps that should be run by MetaDeploy to install Outbound Funds. With this, I can publish a new version by running a command like `cci task run metadeploy_publish -o tag release/1.15` -- this is something that Jason or I will need to do for now, because it requires admin access to MetaDeploy.

The plan includes a check so that OutboundFundsNPSP will be installed if and only if NPSP is installed.

I've already published a draft version of the installer which can be tested at https://install.salesforce.org/products/outbound-funds -- it's possible to add more explanatory text here if you want.

# Critical Changes

# Changes

# Issues Closed

### CODE REVIEW

**Comment by Nickers3** [comment]
@davisagli, this looks really slick.  One thing to mention is we will have instances in which people would only install the core.  It looks as though both are listed as required in the plan.  Could the NPSP Ext be listed in the additional plans section vs. a part of the core plan?

**Comment by Nickers3** [comment]
Also, I tried to use the installer for a developer org and after the pre-install validation completed, I wasn't able to install.  Is that by design?

image

**Comment by davisagli** [comment]
@Nickers3 the pre-install validation checks whether NPSP is installed in the org already. If not, the step for the extension package will be skipped. Is that sufficient to handle the case where only the core should be installed, or are there cases where the org has NPSP but the extension package is not desired?

I'll check why it's not working -- sorry for using you as the guinea pig and not actually trying it myself yet.

**Comment by Nickers3** [comment]
@davisagli, happy to be the guinea pig as this is all really excited to see unfold.  Gotcha on the pre-install validation check and the extension package being dynamic based on NPSP.

There could be situations where someone has NPSP and only use the core.  Most of the time if they have NPSP, they'd want both.  @wcorkill, would you and Shari agree with that statement?

How much effort would it be to allow someone to choose if they want the Extension package?  Might be worth a quick drive by Bill and Shari about this idea.  I'll post on quip to gauge their thoughts.

**Comment by davisagli** [comment]
@Nickers3 we can make the extension package optional, with a checkbox that is checked by default.

**Comment by Nickers3** [comment]
Let's go that route.  I'd rather allow more flexibility.  If Shari or Bill
think differently, I'll let you know.

**Comment by Nickers3** [comment]
@davisagli @wcorkill and Shari agree, let's make the extension package optional.

**Comment by davisagli** [comment]
@Nickers3 the extension package is now optional, and I've figured out a workaround for the bug with the install button remaining disabled.

**Comment by Nickers3** [comment]
@davisagli, one last error I noticed while test - if I had an install error like the attached, I can't re-rerun the precheck validation
Error trying to upgrade from 1.13 to 1.15 (the master detail to lookup change)
image

Unable to re-run the pre-install validation after I went through the install process.
image

**Comment by Nickers3** [comment]
If I refresh the page, I can re-run the validation and install.  So it is just staying on the page that causes the issue.

**Comment by davisagli** [comment]
@Nickers3 Is it all right if I merge this so the repository includes the code that was used to publish the installer that has been live for a while now?

**Comment by Nickers3** [comment]
Sure thing.  Thanks for remembering.

**Pull request merged**
